--- #YAML:1.0
name:               CGI-Inspect
version:            0.2
abstract:           Inspect and debug CGI apps with an in-browser UI
author:
    - Brock Wilcox <awwaiid@thelackthereof.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Continuity:           1.0
    Devel::LexAlias:      0
    Devel::StackTrace::WithLexicals:  0.01
    PadWalker:            0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
